apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.pod.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      name: {{ .Values.pod.name }}
  serviceName: {{ .Values.service.name }}
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        name: {{ .Values.pod.name }}
    spec:
      {{- if .Values.serviceAccount }}
      serviceAccountName: {{ .Values.serviceAccount }}
      {{- end }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key:      "name"
                    operator: In
                    values:
                    - {{ quote .Values.pod.name }}
                    - {{ quote .Values.service.name }}
              topologyKey:    "kubernetes.io/hostname"

      {{- if .Values.logs.storageClassName }}
      volumes:
        - name: {{ .Chart.Name }}-logs
          persistentVolumeClaim:
              claimName: {{ .Chart.Name }}-logs-pvc
      {{- end }}

      containers:
      - image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Values.pod.name }}

        {{- if .Values.logs.storageClassName }}
        volumeMounts:
          - mountPath: "/root/.mongoose/"
            name: {{ .Chart.Name }}-logs
        {{- end }}

        {{- with .Values.resources }}
        resources:
          limits:
            cpu: {{ quote .limits.cpu }}
            memory: {{ quote .limits.memory }}
          requests:
            cpu: {{ quote .requests.cpu }}
            memory: {{ quote .requests.memory }}
        {{- end }}

        args: {{- printf " [" -}}
          {{- printf "\"--run-node\"" -}}
          {{ if (ne $.Values.args "") and (ne $.Values.args nil) }}
            {{- printf "," }}
            {{- .Values.args -}}
          {{ end }}
          {{- printf "]" }}

        ports:
        - containerPort: 1099
        - containerPort: 9999
        {{ if .Values.debug }}
        - containerPort: 5005
        command: ["/opt/mongoose/entrypoint_debug.sh"]
        {{- end }}

