apiVersion: v1
kind: Pod
metadata:
  name: {{ .Chart.Name }}
spec:
  {{- if .Values.serviceAccount }}
  serviceAccountName: {{ .Values.serviceAccount }}
  {{- end }}

  volumes:
  - name: scenario-volume
    configMap:
      name: {{ .Chart.Name }}-scenario-cm
        -
  {{- if .Values.logs.storageClassName }}
  - name: logs-volume
    persistentVolumeClaim:
      claimName: {{ .Chart.Name }}-logs-pvc
  {{- end }}

  initContainers:
  - name: wait-for-services
    image: busybox:1.28
    command: ['sh',
              '-c',
              '{{ template "mongoose.makeShellCommand" . }}'
             ]

  containers:
    - image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      name: {{ .Chart.Name }}
      args: {{- printf " [" -}}
                  
            {{- $nodeCount := ((add (.Values.replicas|int) -1)|int) -}}
            {{- if gt $nodeCount 0 -}}
              {{- printf "\"--load-step-node-addrs=" -}}
              {{- range $index, $e := until $nodeCount -}}
                {{- printf "%s-%d.%s" $.Values.pod.name $index $.Values.service.name -}}
                {{ if ne (add $e 1) $nodeCount }}
                  {{- printf "," -}}
                {{ end }}
              {{- end -}}
              {{- printf "\"," -}}
            {{- end -}}

            {{- printf "\"--run-scenario=/opt/mongoose/scenario.js\"" -}}
            
            {{ if (ne $.Values.args "") and (ne $.Values.args nil) }}
              {{- printf "," }}
              {{- .Values.args -}}
            {{ end }}
            
            {{- printf "]" }}


      {{ if .Values.debug }}
      ports:
      - containerPort: 5005
      command: ["/opt/mongoose/entrypoint_debug.sh"]
      {{- end }}

      volumeMounts:
      - name: scenario-volume
        mountPath: /opt/mongoose/scenario.js
        subPath: scenario.js

      {{- if .Values.logs.storageClassName }}
      - mountPath: "/root/.mongoose/"
        name: logs-volume
      {{- end }}

      {{- with .Values.resources }}
      resources:
        limits:
          cpu: {{ quote .limits.cpu }}
          memory: {{ quote .limits.memory }}
        requests:
          cpu: {{ quote .requests.cpu }}
          memory: {{ quote .requests.memory }}
      {{- end }}



  restartPolicy: OnFailure
