# service only for debug
{{- if .Values.debug }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  {{- if .Values.serviceAccount }}
  serviceAccountName: {{ .Values.serviceAccount }}
  {{- end }}
  type: {{ .Values.service.type }}
  ports:
    - name: debug
      port: 5005
      targetPort: 5005
  selector:
    mongoose-role: entry-node
{{- end }}
