apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.name }}-controller
  labels:
    app: {{ .Chart.Name }}
spec:
  {{- if .Values.serviceAccount }}
  serviceAccountName: {{ .Values.serviceAccount }}
  {{- end }}

  volumes:
  - name: scenario-volume
    configMap:
      name: {{ .Values.name }}-scenario-cm

  initContainers:
  - name: sleep
    image: busybox:1.28
    command: ['sh','-c','sleep 60']

  containers:
    - image: "{{ .Values.controller.image }}:{{ .Values.controller.tag }}"
      imagePullPolicy: {{ .Values.controller.pullPolicy }}
      name: {{ .Values.name }}-controller
      args: {{- printf " [" -}}

            {{- printf "\"--test-scenario-file=/opt/mongoose/scenario\"" -}}
            
            {{ if (ne $.Values.args "") and (ne $.Values.args nil) }}
              {{- printf "," }}
              {{- .Values.args -}}
            {{ end }}
            
            {{- printf "]" }}

      ports:
      - containerPort: 1099

      volumeMounts:
      - name: scenario-volume
        mountPath: /opt/mongoose/scenario
        subPath: scenario

      {{- with .Values.resources }}
      resources:
        limits:
          cpu: {{ quote .limits.cpu }}
          memory: {{ quote .limits.memory }}
        requests:
          cpu: {{ quote .requests.cpu }}
          memory: {{ quote .requests.memory }}
      {{- end }}

  restartPolicy: OnFailure
