apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.name }}-tmp
  labels:
    app: {{ .Chart.Name }}
spec:
  {{- if .Values.serviceAccount }}
  serviceAccountName: {{ .Values.serviceAccount }}
  {{- end }}

  volumes:
  - name: scenario-volume
    configMap:
      name: {{ .Values.name }}-scenario-cm

  initContainers:
  - name: sleep
    image: busybox:1.28
    command: ['sh','-c','sleep 60']

  containers:
    - image: busybox:1.28
      name: {{ .Values.name }}-tmp
      args: ['sh','-c','sleep 100000']


      volumeMounts:
      - name: scenario-volume
        mountPath: /opt/mongoose/scenario
        subPath: scenario

      {{- with .Values.resources }}
      resources:
        limits:
          cpu: {{ quote .limits.cpu }}
          memory: {{ quote .limits.memory }}
        requests:
          cpu: {{ quote .requests.cpu }}
          memory: {{ quote .requests.memory }}
      {{- end }}

  restartPolicy: OnFailure
