apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}
spec:
  {{- if .Values.serviceAccount }}
  serviceAccountName: {{ .Values.serviceAccount }}
  {{- end }}
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      name: {{ .Values.name }}
  serviceName: {{ .Values.service.name }}
  podManagementPolicy: Parallel

  template:
    metadata:
      labels:
        name: {{ .Values.name }}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key:      "name"
                    operator: In
                    values:
                    - {{ quote .Values.name }}
                    - {{ quote .Values.service.name }}
              topologyKey:    "kubernetes.io/hostname"
      containers:
        - image: "{{ .Values.image.worker }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Values.name }}
          args: ["--run-node"]

          {{- with .Values.resources }}
          resources:
            limits:
              cpu: {{ quote .limits.cpu }}
              memory: {{ quote .limits.memory }}
            requests:
              cpu: {{ quote .requests.cpu }}
              memory: {{ quote .requests.memory }}
          {{- end }}

          ports:
          - containerPort: 1099
